### ISSUE TITLE
vue怎么引用

### ISSUE THREAD

**Issue by lilingzhisunge** [wanxiaodong404/picture2color#2]
![image](https://user-images.githubusercontent.com/47549443/104539328-40405200-5658-11eb-8b66-13a5a4a96bc4.png)
他老是报这样的错误，可以帮忙看看是为什么么

**Comment by lilingzhisunge** [comment]
[
![image](https://user-images.githubusercontent.com/47549443/104539381-5a7a3000-5658-11eb-87c2-a94aba48570c.png)
](url)

**Comment by lilingzhisunge** [comment]
就是This dependency was not found:
                                                                                                                                                              cache-loader@4.1.0@cache-loader/dis
* picture2color in ./node_modules/_cache-loader@4.1.0@cache-loader/dist/cjs.js??ref--12-0!./node_modules/_babel-loader@8.2.2@babel-loader/lib!./node_modules/_cache-loader@4.1.0@cache-loader/dist/cjs.js??ref--0-0!./node_modules/_vue-loader@15.9.6@vue-loader/lib??vue-loader-options!./src/views/taskManage/VD-Task/detail.vue?vue&type=script&lang=js&

To install it, you can run: npm install --save picture2color

**Comment by wanxiaodong404** [comment]
可以按照提示执行 npm install --save picture2color试试

**Comment by wanxiaodong404** [comment]
已经在0.1.3版本修复，🙏
